services:
  backend:
    build: .
    container_name: artgallery-backend
    env_file:
      - ./env/local.env
    ports:
      - '3000:3000'
    # volumes:
    #   - .:/app   âŒ This breaks your container
    restart: unless-stopped
